name: test
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        perl:
          [
            "5.38",
            "5.36",
            "5.34",
            "5.32",
            "5.30",
            "5.22",
          ]
    name: Perl ${{ matrix.perl }}
    services:
      postgres:
        image: postgres:16-alpine
        env:
          POSTGRES_DATABASE: catmandu_dbi
          POSTGRES_USER: catmandu_dbi
          POSTGRES_PASSWORD: catmandu_dbi
          # see section on PGDATA in https://hub.docker.com/_/postgres
          PGDATA: /var/lib/postgresql/data/pgdata
          PGPORT: 5432
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    env:
      MYSQL_DATABASE: catmandu_dbi
      MYSQL_USER: catmandu_dbi
      MYSQL_PASSWORD: catmandu_dbi
      MYSQL_ROOT_PASSWORD: catmandu_dbi
      MYSQL_CHARSET: utf8
      MYSQL_COLLATION: utf8_general_ci
    steps:
      - uses: actions/checkout@v3
      # mysql is preinstalled
      - name: Setup mysql
        run: |
          sudo /etc/init.d/mysql start
          mysql -e 'CREATE DATABASE ${{ env.MYSQL_DATABASE }};' -uroot -proot
      - name: Setup perl
        uses: shogo82148/actions-setup-perl@v1
        with:
          perl-version: ${{ matrix.perl }}      
      - name: Install dependencies
        run: cpanm -nq --installdeps --with-develop --with-recommends --with-all-features .
      - name: Run test
        shell: bash
        run: |
          export CATMANDU_DBI_TEST_PG_DSN="dbi:Pg:dbname=catmandu_dbi;host=localhost"
          export CATMANDU_DBI_TEST_PG_USERNAME=catmandu_dbi
          export CATMANDU_DBI_TEST_PG_PASSWORD=catmandu_dbi
          export CATMANDU_DBI_TEST_MYSQL_DSN="dbi:mysql:database=catmandu_dbi"
          export CATMANDU_DBI_TEST_MYSQL_USERNAME=root
          export CATMANDU_DBI_TEST_MYSQL_PASSWORD=root
          prove -lr t
